services:
  postgres:
    image: 'bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=smart_home
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432